### ISSUE TITLE
User needs to see a change the moment they select a network

### ISSUE THREAD

**Issue by seanPhill** [dingocoin/wdingocoin-frontend#7]
The layout looks really beautiful in the initial display, but when the button underneath "Select Network Below"  is clicked, the extra line breaks need to disappear to make room to see that something has changed. Currently it looks like nothing has changed, so the user will keep clicking and then hit refresh and decide the page does not work!

By removing the extra line breaks IMMEDIATELY AFTER the network is selected the user will see the following content and will scroll further to see it.

**Comment by seanPhill** [comment]
If you want it to look really fancy and slick as it gradually moves the lines in the first section of the page closer together, and maybe deemphasises the text "Select Network Below", as the network has already been selected, then go right ahead, but that can be for another day.

**Comment by BobTheBuilderSTD** [comment]
Has been Resolved.
